# Pandas Data Analysis Practice

*This assignment is a part of the course ["Data Analysis with Python: Zero to Pandas"](https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas)*

In this assignment, you'll get to practice some of the concepts and skills covered this tutorial: https://jovian.ml/aakashns/python-pandas-data-analysis

As you go through this notebook, you will find a **???** in certain places. To complete this assignment, you must replace all the **???** with appropriate values, expressions or statements to ensure that the notebook runs properly end-to-end. 

Some things to keep in mind:

* Make sure to run all the code cells, otherwise you may get errors like `NameError` for undefined variables.
* Do not change variable names, delete cells or disturb other existing code. It may cause problems during evaluation.
* In some cases, you may need to add some code cells or new statements before or after the line of code containing the **???**. 
* Since you'll be using a temporary online service for code execution, save your work by running `jovian.commit` at regular intervals.
* Questions marked **(Optional)** will not be considered for evaluation, and can be skipped. They are for your learning.

You can make submissions on this page: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-3-pandas-practice

If you are stuck, you can ask for help on the community forum: https://jovian.ml/forum/t/assignment-3-pandas-practice/11225/3 . You can get help with errors or ask for hints, describe your approach in simple words, link to documentation, but **please don't ask for or share the full working answer code** on the forum.


## How to run the code and save your work

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on [mybinder.org](https://mybinder.org), a free online service for running Jupyter notebooks. 

Before staring the assignment, let's save a snapshot of the assignment to your Jovian.ml profile, so that you can access it later, and continue your work.

In [ ]:
import jovian

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

In [ ]:
# Run the next line to install Pandas
!pip install pandas --upgrade

In [ ]:
import pandas as pd

In this assignment, we're going to analyze an operate on data from a CSV file. Let's begin by downloading the CSV file.

In [ ]:
from urllib.request import urlretrieve

urlretrieve('https://hub.jovian.ml/wp-content/uploads/2020/09/countries.csv', 
            'countries.csv')

('countries.csv', <http.client.HTTPMessage at 0x7fd5ca6b4048>)

Let's load the data from the CSV file into a Pandas data frame.

In [ ]:
countries_df = pd.read_csv('countries.csv')

In [ ]:
countries_df

           location continent  ...  hospital_beds_per_thousand  gdp_per_capita
0       Afghanistan      Asia  ...                        0.50        1803.987
1           Albania    Europe  ...                        2.89       11803.431
2           Algeria    Africa  ...                        1.90       13913.839
3           Andorra    Europe  ...                         NaN             NaN
4            Angola    Africa  ...                         NaN        5819.495
..              ...       ...  ...                         ...             ...
205         Vietnam      Asia  ...                        2.60        6171.884
206  Western Sahara    Africa  ...                         NaN             NaN
207           Yemen      Asia  ...                        0.70        1479.147
208          Zambia    Africa  ...                        2.00        3689.251
209        Zimbabwe    Africa  ...                        1.70        1899.775

[210 rows x 6 columns]

**Q: How many countries does the dataframe contain?**

Hint: Use the `.shape` method.

In [ ]:
num_countries = countries_df.shape[0]

In [ ]:
print('There are {} countries in the dataset'.format(num_countries))

There are 210 countries in the dataset

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

**Q: Retrieve a list of continents from the dataframe?**

*Hint: Use the `.unique` method of a series.*

In [ ]:
continents = pd.unique(countries_df['continent'])

In [ ]:
continents

array(['Asia', 'Europe', 'Africa', 'North America', 'South America',
       'Oceania'], dtype=object)

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

**Q: What is the total population of all the countries listed in this dataset?**

In [ ]:
total_population = pd.unique(countries_df['population']).sum()

In [ ]:
print('The total population is {}.'.format(int(total_population)))

The total population is 7757980095.

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

**Q: (Optional) What is the overall life expectancy across in the world?**

*Hint: You'll need to take a weighted average of life expectancy using populations as weights.*

In [ ]:
countries_df

           location continent  ...  gdp_per_capita           gdp
0       Afghanistan      Asia  ...        1803.987  7.022622e+10
1           Albania    Europe  ...       11803.431  3.396791e+10
2           Algeria    Africa  ...       13913.839  6.101364e+11
3           Andorra    Europe  ...             NaN           NaN
4            Angola    Africa  ...        5819.495  1.912651e+11
..              ...       ...  ...             ...           ...
205         Vietnam      Asia  ...        6171.884  6.007624e+11
206  Western Sahara    Africa  ...             NaN           NaN
207           Yemen      Asia  ...        1479.147  4.411699e+10
208          Zambia    Africa  ...        3689.251  6.782303e+10
209        Zimbabwe    Africa  ...        1899.775  2.823622e+10

[210 rows x 7 columns]

In [ ]:
world_life_expectancy = (countries_df['life_expectancy'] * countries_df['population']).sum() / pd.unique(countries_df['population']).sum()

In [ ]:
print('The overall life expectancy across in the world is {}.'.format(float(world_life_expectancy)))

The overall life expectancy across in the world is 72.72165193409664.

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

**Q: Create a dataframe containing 10 countries with the highest population.**

*Hint: Chain the `sort_values` and `head` methods.*

In [ ]:
most_populous_df = countries_df.sort_values('population', ascending=False).head(10)

In [ ]:
most_populous_df

          location      continent  ...  gdp_per_capita           gdp
41           China           Asia  ...       15308.712  2.203419e+13
90           India           Asia  ...        6426.674  8.868838e+12
199  United States  North America  ...       54225.446  1.794877e+13
91       Indonesia           Asia  ...       11188.744  3.060386e+12
145       Pakistan           Asia  ...        5034.708  1.112128e+12
27          Brazil  South America  ...       14103.452  2.997821e+12
141        Nigeria         Africa  ...        5338.454  1.100467e+12
15      Bangladesh           Asia  ...        3523.984  5.803628e+11
157         Russia         Europe  ...       24765.954  3.614206e+12
125         Mexico  North America  ...       17336.469  2.235239e+12

[10 rows x 7 columns]

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

**Q: Add a new column in `countries_df` to record the overall GDP per country (product of population & per capita GDP).**

In [ ]:
countries_df.population * countries_df.gdp_per_capita

0      7.022622e+10
1      3.396791e+10
2      6.101364e+11
3               NaN
4      1.912651e+11
           ...
205    6.007624e+11
206             NaN
207    4.411699e+10
208    6.782303e+10
209    2.823622e+10
Length: 210, dtype: float64

In [ ]:
countries_df['gdp'] = countries_df.population * countries_df.gdp_per_capita

In [ ]:
countries_df

           location continent  ...  gdp_per_capita           gdp
0       Afghanistan      Asia  ...        1803.987  7.022622e+10
1           Albania    Europe  ...       11803.431  3.396791e+10
2           Algeria    Africa  ...       13913.839  6.101364e+11
3           Andorra    Europe  ...             NaN           NaN
4            Angola    Africa  ...        5819.495  1.912651e+11
..              ...       ...  ...             ...           ...
205         Vietnam      Asia  ...        6171.884  6.007624e+11
206  Western Sahara    Africa  ...             NaN           NaN
207           Yemen      Asia  ...        1479.147  4.411699e+10
208          Zambia    Africa  ...        3689.251  6.782303e+10
209        Zimbabwe    Africa  ...        1899.775  2.823622e+10

[210 rows x 7 columns]

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

**Q: (Optional) Create a dataframe containing 10 countries with the lowest GDP per capita, among the counties with population greater than 100 million.**

In [ ]:
countries_more_100mill_df = countries_df[countries_df.population > 100e6] 
countries_more_100mill_df

          location      continent  ...  gdp_per_capita           gdp
15      Bangladesh           Asia  ...        3523.984  5.803628e+11
27          Brazil  South America  ...       14103.452  2.997821e+12
41           China           Asia  ...       15308.712  2.203419e+13
58           Egypt         Africa  ...       10550.206  1.079649e+12
63        Ethiopia         Africa  ...        1729.927  1.988786e+11
90           India           Asia  ...        6426.674  8.868838e+12
91       Indonesia           Asia  ...       11188.744  3.060386e+12
99           Japan           Asia  ...       39002.223  4.932863e+12
125         Mexico  North America  ...       17336.469  2.235239e+12
141        Nigeria         Africa  ...        5338.454  1.100467e+12
145       Pakistan           Asia  ...        5034.708  1.112128e+12
151    Philippines           Asia  ...        7599.188  8.327273e+11
157         Russia         Europe  ...       24765.954  3.614206e+12
199  United States  North America  ...       54225.446  1.794877e+13

[14 rows x 7 columns]

In [ ]:
countries_lowGDP_from_more_100mill_df = countries_more_100mill_df.sort_values('gdp').head(10)
countries_lowGDP_from_more_100mill_df

        location      continent  ...  gdp_per_capita           gdp
63      Ethiopia         Africa  ...        1729.927  1.988786e+11
15    Bangladesh           Asia  ...        3523.984  5.803628e+11
151  Philippines           Asia  ...        7599.188  8.327273e+11
58         Egypt         Africa  ...       10550.206  1.079649e+12
141      Nigeria         Africa  ...        5338.454  1.100467e+12
145     Pakistan           Asia  ...        5034.708  1.112128e+12
125       Mexico  North America  ...       17336.469  2.235239e+12
27        Brazil  South America  ...       14103.452  2.997821e+12
91     Indonesia           Asia  ...       11188.744  3.060386e+12
157       Russia         Europe  ...       24765.954  3.614206e+12

[10 rows x 7 columns]

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

**Q: Create a data frame that counts the number countries in each continent?**

*Hint: Use `groupby`, select the `location` column and aggregate using `count`.*

In [ ]:
country_counts_df = countries_df.groupby('continent')['location'].count()

In [ ]:
country_counts_df

continent
Africa           55
Asia             47
Europe           51
North America    36
Oceania           8
South America    13
Name: location, dtype: int64

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

**Q: Create a data frame showing the total population of each continent.**

*Hint: Use `groupby`, select the population column and aggregate using `sum`.*

In [ ]:
continent_populations_df = countries_df.groupby('continent')['population'].sum()

In [ ]:
continent_populations_df

continent
Africa           1.339424e+09
Asia             4.607388e+09
Europe           7.485062e+08
North America    5.912425e+08
Oceania          4.095832e+07
South America    4.304611e+08
Name: population, dtype: float64

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

Let's download another CSV file containing overall Covid-19 stats for various countires, and read the data into another Pandas data frame.

In [ ]:
urlretrieve('https://hub.jovian.ml/wp-content/uploads/2020/09/covid-countries-data.csv', 
            'covid-countries-data.csv')

('covid-countries-data.csv', <http.client.HTTPMessage at 0x7fd5bf385ba8>)

In [ ]:
covid_data_df = pd.read_csv('covid-countries-data.csv')

In [ ]:
covid_data_df

           location  total_cases  total_deaths  total_tests
0       Afghanistan      38243.0        1409.0          NaN
1           Albania       9728.0         296.0          NaN
2           Algeria      45158.0        1525.0          NaN
3           Andorra       1199.0          53.0          NaN
4            Angola       2729.0         109.0          NaN
..              ...          ...           ...          ...
207  Western Sahara        766.0           1.0          NaN
208           World   26059065.0      863535.0          NaN
209           Yemen       1976.0         571.0          NaN
210          Zambia      12415.0         292.0          NaN
211        Zimbabwe       6638.0         206.0      97272.0

[212 rows x 4 columns]

**Q: Count the number of countries for which the `total_tests` data is missing.**

*Hint: Use the `.isna` method.*

In [ ]:
covid_data_df['total_tests'].isna().sum()

122

In [ ]:
total_tests_missing = covid_data_df['total_tests'].isna().sum()

In [ ]:
print("The data for total tests is missing for {} countries.".format(int(total_tests_missing)))

The data for total tests is missing for 122 countries.

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

Let's merge the two data frames, and compute some more metrics.

**Q: Merge `countries_df` with `covid_data_df` on the `location` column.**

*Hint: Use the `.merge` method on `countries_df`.

In [ ]:
countries_df

           location continent  ...  gdp_per_capita           gdp
0       Afghanistan      Asia  ...        1803.987  7.022622e+10
1           Albania    Europe  ...       11803.431  3.396791e+10
2           Algeria    Africa  ...       13913.839  6.101364e+11
3           Andorra    Europe  ...             NaN           NaN
4            Angola    Africa  ...        5819.495  1.912651e+11
..              ...       ...  ...             ...           ...
205         Vietnam      Asia  ...        6171.884  6.007624e+11
206  Western Sahara    Africa  ...             NaN           NaN
207           Yemen      Asia  ...        1479.147  4.411699e+10
208          Zambia    Africa  ...        3689.251  6.782303e+10
209        Zimbabwe    Africa  ...        1899.775  2.823622e+10

[210 rows x 7 columns]

In [ ]:
covid_data_df

           location  total_cases  total_deaths  total_tests
0       Afghanistan      38243.0        1409.0          NaN
1           Albania       9728.0         296.0          NaN
2           Algeria      45158.0        1525.0          NaN
3           Andorra       1199.0          53.0          NaN
4            Angola       2729.0         109.0          NaN
..              ...          ...           ...          ...
207  Western Sahara        766.0           1.0          NaN
208           World   26059065.0      863535.0          NaN
209           Yemen       1976.0         571.0          NaN
210          Zambia      12415.0         292.0          NaN
211        Zimbabwe       6638.0         206.0      97272.0

[212 rows x 4 columns]

In [ ]:
countries_df.merge(covid_data_df, on="location")

           location continent  ...  total_deaths  total_tests
0       Afghanistan      Asia  ...        1409.0          NaN
1           Albania    Europe  ...         296.0          NaN
2           Algeria    Africa  ...        1525.0          NaN
3           Andorra    Europe  ...          53.0          NaN
4            Angola    Africa  ...         109.0          NaN
..              ...       ...  ...           ...          ...
205         Vietnam      Asia  ...          35.0     261004.0
206  Western Sahara    Africa  ...           1.0          NaN
207           Yemen      Asia  ...         571.0          NaN
208          Zambia    Africa  ...         292.0          NaN
209        Zimbabwe    Africa  ...         206.0      97272.0

[210 rows x 10 columns]

In [ ]:
combined_df = countries_df.merge(covid_data_df, on="location")

In [ ]:
combined_df

           location continent  ...  total_deaths  total_tests
0       Afghanistan      Asia  ...        1409.0          NaN
1           Albania    Europe  ...         296.0          NaN
2           Algeria    Africa  ...        1525.0          NaN
3           Andorra    Europe  ...          53.0          NaN
4            Angola    Africa  ...         109.0          NaN
..              ...       ...  ...           ...          ...
205         Vietnam      Asia  ...          35.0     261004.0
206  Western Sahara    Africa  ...           1.0          NaN
207           Yemen      Asia  ...         571.0          NaN
208          Zambia    Africa  ...         292.0          NaN
209        Zimbabwe    Africa  ...         206.0      97272.0

[210 rows x 10 columns]

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

**Q: Add columns `tests_per_million`, `cases_per_million` and `deaths_per_million` into `combined_df`.**

In [ ]:
combined_df['tests_per_million'] = combined_df['total_tests'] * 1e6 / combined_df['population']

In [ ]:
combined_df['cases_per_million'] = combined_df['total_cases'] * 1e6 / combined_df['population']

In [ ]:
combined_df['deaths_per_million'] = combined_df['total_deaths'] * 1e6 / combined_df['population']

In [ ]:
combined_df

           location continent  ...  cases_per_million  deaths_per_million
0       Afghanistan      Asia  ...         982.394806           36.194710
1           Albania    Europe  ...        3380.359997          102.856349
2           Algeria    Africa  ...        1029.804468           34.776824
3           Andorra    Europe  ...       15518.022390          685.950948
4            Angola    Africa  ...          83.033462            3.316470
..              ...       ...  ...                ...                 ...
205         Vietnam      Asia  ...          10.745996            0.359570
206  Western Sahara    Africa  ...        1282.373228            1.674116
207           Yemen      Asia  ...          66.250993           19.144391
208          Zambia    Africa  ...         675.317108           15.883415
209        Zimbabwe    Africa  ...         446.614587           13.859989

[210 rows x 13 columns]

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

**Q: Create a dataframe with 10 countires that have highest number of tests per million people.**

In [ ]:
 combined_df.sort_values('tests_per_million', ascending=False).head(10)

                 location      continent  ...  cases_per_million  deaths_per_million
197  United Arab Emirates           Asia  ...        7233.276713           39.128852
14                Bahrain           Asia  ...       30818.361490          111.660730
115            Luxembourg         Europe  ...       12665.022301          198.090662
122                 Malta         Europe  ...        4373.339614           29.442473
53                Denmark         Europe  ...        2968.645954          108.076323
96                 Israel           Asia  ...       14157.289533          111.951408
89                Iceland         Europe  ...        6215.384615           29.304029
157                Russia         Europe  ...        6886.653091          119.327539
199         United States  North America  ...       18472.377957          561.155633
10              Australia        Oceania  ...        1016.592979           26.000121

[10 rows x 13 columns]

In [ ]:
highest_tests_df = combined_df.sort_values('tests_per_million', ascending=False).head(10)

In [ ]:
highest_tests_df

                 location      continent  ...  cases_per_million  deaths_per_million
197  United Arab Emirates           Asia  ...        7233.276713           39.128852
14                Bahrain           Asia  ...       30818.361490          111.660730
115            Luxembourg         Europe  ...       12665.022301          198.090662
122                 Malta         Europe  ...        4373.339614           29.442473
53                Denmark         Europe  ...        2968.645954          108.076323
96                 Israel           Asia  ...       14157.289533          111.951408
89                Iceland         Europe  ...        6215.384615           29.304029
157                Russia         Europe  ...        6886.653091          119.327539
199         United States  North America  ...       18472.377957          561.155633
10              Australia        Oceania  ...        1016.592979           26.000121

[10 rows x 13 columns]

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

**Q: Create a dataframe with 10 countires that have highest number of positive cases per million people.**

In [ ]:
combined_df.sort_values('cases_per_million', ascending=False).head(10)

          location      continent  ...  cases_per_million  deaths_per_million
155          Qatar           Asia  ...       41375.743650           69.071800
14         Bahrain           Asia  ...       30818.361490          111.660730
147         Panama  North America  ...       21805.112117          470.477208
40           Chile  South America  ...       21695.671982          593.423100
162     San Marino         Europe  ...       21657.139490         1237.550828
9            Aruba  North America  ...       20708.839893          112.395332
105         Kuwait           Asia  ...       20249.789079          125.276222
150           Peru  South America  ...       20121.318048          887.393445
27          Brazil  South America  ...       18808.224105          582.331314
199  United States  North America  ...       18472.377957          561.155633

[10 rows x 13 columns]

In [ ]:
highest_cases_df = combined_df.sort_values('cases_per_million', ascending=False).head(10)

In [ ]:
highest_cases_df

          location      continent  ...  cases_per_million  deaths_per_million
155          Qatar           Asia  ...       41375.743650           69.071800
14         Bahrain           Asia  ...       30818.361490          111.660730
147         Panama  North America  ...       21805.112117          470.477208
40           Chile  South America  ...       21695.671982          593.423100
162     San Marino         Europe  ...       21657.139490         1237.550828
9            Aruba  North America  ...       20708.839893          112.395332
105         Kuwait           Asia  ...       20249.789079          125.276222
150           Peru  South America  ...       20121.318048          887.393445
27          Brazil  South America  ...       18808.224105          582.331314
199  United States  North America  ...       18472.377957          561.155633

[10 rows x 13 columns]

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

**Q: Create a dataframe with 10 countires that have highest number of deaths cases per million people?**

In [ ]:
combined_df.sort_values('deaths_per_million', ascending=False).head(10)

           location      continent  ...  cases_per_million  deaths_per_million
162      San Marino         Europe  ...       21657.139490         1237.550828
150            Peru  South America  ...       20121.318048          887.393445
18          Belgium         Europe  ...        7404.645676          854.040375
3           Andorra         Europe  ...       15518.022390          685.950948
177           Spain         Europe  ...       10256.790198          624.406705
198  United Kingdom         Europe  ...        4988.892850          611.525168
40            Chile  South America  ...       21695.671982          593.423100
97            Italy         Europe  ...        4490.684602          587.097697
27           Brazil  South America  ...       18808.224105          582.331314
182          Sweden         Europe  ...        8370.109919          576.279276

[10 rows x 13 columns]

In [ ]:
highest_deaths_df = combined_df.sort_values('deaths_per_million', ascending=False).head(10)

In [ ]:
highest_deaths_df

           location      continent  ...  cases_per_million  deaths_per_million
162      San Marino         Europe  ...       21657.139490         1237.550828
150            Peru  South America  ...       20121.318048          887.393445
18          Belgium         Europe  ...        7404.645676          854.040375
3           Andorra         Europe  ...       15518.022390          685.950948
177           Spain         Europe  ...       10256.790198          624.406705
198  United Kingdom         Europe  ...        4988.892850          611.525168
40            Chile  South America  ...       21695.671982          593.423100
97            Italy         Europe  ...        4490.684602          587.097697
27           Brazil  South America  ...       18808.224105          582.331314
182          Sweden         Europe  ...        8370.109919          576.279276

[10 rows x 13 columns]

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

**(Optional) Q: Count number of countries that feature in both the lists of "highest number of tests per million" and "highest number of cases per million".**

In [ ]:
highest_tests_df

                 location      continent  ...  cases_per_million  deaths_per_million
197  United Arab Emirates           Asia  ...        7233.276713           39.128852
14                Bahrain           Asia  ...       30818.361490          111.660730
115            Luxembourg         Europe  ...       12665.022301          198.090662
122                 Malta         Europe  ...        4373.339614           29.442473
53                Denmark         Europe  ...        2968.645954          108.076323
96                 Israel           Asia  ...       14157.289533          111.951408
89                Iceland         Europe  ...        6215.384615           29.304029
157                Russia         Europe  ...        6886.653091          119.327539
199         United States  North America  ...       18472.377957          561.155633
10              Australia        Oceania  ...        1016.592979           26.000121

[10 rows x 13 columns]

In [ ]:
highest_cases_df

          location      continent  ...  cases_per_million  deaths_per_million
155          Qatar           Asia  ...       41375.743650           69.071800
14         Bahrain           Asia  ...       30818.361490          111.660730
147         Panama  North America  ...       21805.112117          470.477208
40           Chile  South America  ...       21695.671982          593.423100
162     San Marino         Europe  ...       21657.139490         1237.550828
9            Aruba  North America  ...       20708.839893          112.395332
105         Kuwait           Asia  ...       20249.789079          125.276222
150           Peru  South America  ...       20121.318048          887.393445
27          Brazil  South America  ...       18808.224105          582.331314
199  United States  North America  ...       18472.377957          561.155633

[10 rows x 13 columns]

In [ ]:
countries_high_test_cases_df = highest_tests_df.merge(highest_cases_df, on='location')
countries_high_test_cases_df

        location    continent_x  ...  cases_per_million_y  deaths_per_million_y
0        Bahrain           Asia  ...         30818.361490            111.660730
1  United States  North America  ...         18472.377957            561.155633

[2 rows x 25 columns]

In [ ]:
num_countries_high_test_cases = countries_high_test_cases_df.count().location
num_countries_high_test_cases

2

In [ ]:
print('The number of countries that feature in both the lists of \n"highest number of tests per million" and \n"highest number of cases per million" is {}.'.format(int(num_countries_high_test_cases)))

The number of countries that feature in both the lists of
"highest number of tests per million" and
"highest number of cases per million" is 2.

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

**(Optional) Q: Count number of countries that feature in both the lists "20 countries with lowest GDP per capita" and "20 countries with the lowest number of hospital beds per thousand population". Only consider countries with a population higher than 10 million while creating the list.**

In [ ]:
countries_more_10mill_df = countries_df[countries_df.population > 10e6]
countries_more_10mill_df

        location      continent  ...  gdp_per_capita           gdp
0    Afghanistan           Asia  ...        1803.987  7.022622e+10
2        Algeria         Africa  ...       13913.839  6.101364e+11
4         Angola         Africa  ...        5819.495  1.912651e+11
7      Argentina  South America  ...       18933.907  8.557326e+11
10     Australia        Oceania  ...       44648.710  1.138537e+12
..           ...            ...  ...             ...           ...
204    Venezuela  South America  ...       16745.022  4.761605e+11
205      Vietnam           Asia  ...        6171.884  6.007624e+11
207        Yemen           Asia  ...        1479.147  4.411699e+10
208       Zambia         Africa  ...        3689.251  6.782303e+10
209     Zimbabwe         Africa  ...        1899.775  2.823622e+10

[90 rows x 7 columns]

In [ ]:
countries_more_10mill_low_GDP_percapita_df = countries_more_10mill_df.sort_values('gdp_per_capita', ascending=True).head(20)
countries_more_10mill_low_GDP_percapita_df

                         location      continent  ...  gdp_per_capita           gdp
32                        Burundi         Africa  ...         702.225  8.350004e+09
52   Democratic Republic of Congo         Africa  ...         808.133  7.237753e+10
140                         Niger         Africa  ...         926.000  2.241534e+10
118                        Malawi         Africa  ...        1095.042  2.094810e+10
132                    Mozambique         Africa  ...        1136.103  3.550939e+10
117                    Madagascar         Africa  ...        1416.440  3.922267e+10
207                         Yemen           Asia  ...        1479.147  4.411699e+10
176                   South Sudan         Africa  ...        1569.888  1.757290e+10
85                          Haiti  North America  ...        1653.173  1.885036e+10
195                        Uganda         Africa  ...        1697.707  7.765482e+10
31                   Burkina Faso         Africa  ...        1703.102  3.560041e+10
63                       Ethiopia         Africa  ...        1729.927  1.988786e+11
39                           Chad         Africa  ...        1768.153  2.904343e+10
0                     Afghanistan           Asia  ...        1803.987  7.022622e+10
158                        Rwanda         Africa  ...        1854.211  2.401613e+10
209                      Zimbabwe         Africa  ...        1899.775  2.823622e+10
82                         Guinea         Africa  ...        1998.926  2.625148e+10
121                          Mali         Africa  ...        2014.306  4.079138e+10
20                          Benin         Africa  ...        2064.236  2.502514e+10
135                         Nepal           Asia  ...        2442.804  7.117551e+10

[20 rows x 7 columns]

In [ ]:
countries_more_10mill_low_hospital_beds_per_thousan_df = countries_more_10mill_df.sort_values('hospital_beds_per_thousand', ascending=True).head(20)
countries_more_10mill_low_hospital_beds_per_thousan_df

         location      continent  ...  gdp_per_capita           gdp
121          Mali         Africa  ...        2014.306  4.079138e+10
117    Madagascar         Africa  ...        1416.440  3.922267e+10
140         Niger         Africa  ...         926.000  2.241534e+10
135         Nepal           Asia  ...        2442.804  7.117551e+10
82         Guinea         Africa  ...        1998.926  2.625148e+10
63       Ethiopia         Africa  ...        1729.927  1.988786e+11
31   Burkina Faso         Africa  ...        1703.102  3.560041e+10
195        Uganda         Africa  ...        1697.707  7.765482e+10
0     Afghanistan           Asia  ...        1803.987  7.022622e+10
20          Benin         Africa  ...        2064.236  2.502514e+10
90          India           Asia  ...        6426.674  8.868838e+12
80      Guatemala  North America  ...        7423.808  1.330017e+11
145      Pakistan           Asia  ...        5034.708  1.112128e+12
85          Haiti  North America  ...        1653.173  1.885036e+10
207         Yemen           Asia  ...        1479.147  4.411699e+10
187      Tanzania         Africa  ...        2683.304  1.602851e+11
132    Mozambique         Africa  ...        1136.103  3.550939e+10
32        Burundi         Africa  ...         702.225  8.350004e+09
33       Cambodia           Asia  ...        3645.070  6.094182e+10
204     Venezuela  South America  ...       16745.022  4.761605e+11

[20 rows x 7 columns]

In [ ]:
countries_more_10mill_featuring_both_lowGDP_beds_df = countries_more_10mill_low_GDP_percapita_df.merge(countries_more_10mill_low_hospital_beds_per_thousan_df, on='location')
countries_more_10mill_featuring_both_lowGDP_beds_df

        location    continent_x  ...  gdp_per_capita_y         gdp_y
0        Burundi         Africa  ...           702.225  8.350004e+09
1          Niger         Africa  ...           926.000  2.241534e+10
2     Mozambique         Africa  ...          1136.103  3.550939e+10
3     Madagascar         Africa  ...          1416.440  3.922267e+10
4          Yemen           Asia  ...          1479.147  4.411699e+10
5          Haiti  North America  ...          1653.173  1.885036e+10
6         Uganda         Africa  ...          1697.707  7.765482e+10
7   Burkina Faso         Africa  ...          1703.102  3.560041e+10
8       Ethiopia         Africa  ...          1729.927  1.988786e+11
9    Afghanistan           Asia  ...          1803.987  7.022622e+10
10        Guinea         Africa  ...          1998.926  2.625148e+10
11          Mali         Africa  ...          2014.306  4.079138e+10
12         Benin         Africa  ...          2064.236  2.502514e+10
13         Nepal           Asia  ...          2442.804  7.117551e+10

[14 rows x 13 columns]

In [ ]:
num_countries_more_10mill_featuring_both_lowGDP_beds = countries_more_10mill_featuring_both_lowGDP_beds_df.count().location
num_countries_more_10mill_featuring_both_lowGDP_beds

14

In [ ]:
print('The number of countries that feature in both the lists \n"20 countries with lowest GDP per capita" and \n"20 countries with the lowest number of hospital beds \nper thousand population" is {}.'.format(int(num_countries_more_10mill_featuring_both_lowGDP_beds)))

The number of countries that feature in both the lists
"20 countries with lowest GDP per capita" and
"20 countries with the lowest number of hospital beds
per thousand population" is 14.

In [ ]:
import jovian

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

[jovian] Attempting to save notebook..

## Submission 

Congratulations on making it this far! You've reached the end of this assignment, and you just completed your first real-world data analysis problem. It's time to record one final version of your notebook for submission.

Make a submission here by filling the submission form: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-3-pandas-practice

Also make sure to help others on the forum: https://jovian.ml/forum/t/assignment-3-pandas-practice/11225/2